import { createStatBlock } from "../gameplay/stats";
import type { EnemyDefinition } from "../gameplay/types";

export const enemyDefinitions: Record<string, EnemyDefinition> = {
  scavenger: {
    id: "scavenger",
    name: "Scavenger Rusher",
    archetype: "rusher",
    color: 0xbf7040,
    radius: 16,
    baseStats: createStatBlock({
      maxHealth: 48,
      healthRegen: 0,
      maxEnergy: 0,
      energyRegen: 0,
      armor: 5,
      moveSpeed: 98,
      attackSpeed: 1,
      physicalDamageMin: 4,
      physicalDamageMax: 7,
      fireDamageMin: 0,
      fireDamageMax: 0,
      critChance: 0.02,
      critMultiplier: 1.5,
      physicalResistance: 0.03,
      fireResistance: 0.02,
    }),
    xpReward: 22,
    contactDamageMin: 5,
    contactDamageMax: 8,
    attackRange: 36,
    attackCooldownMs: 1200,
  },
  cultist: {
    id: "cultist",
    name: "Ash Cultist",
    archetype: "ranged",
    color: 0x8f68d7,
    radius: 16,
    baseStats: createStatBlock({
      maxHealth: 42,
      healthRegen: 0,
      maxEnergy: 0,
      energyRegen: 0,
      armor: 4,
      moveSpeed: 84,
      attackSpeed: 1,
      physicalDamageMin: 2,
      physicalDamageMax: 4,
      fireDamageMin: 5,
      fireDamageMax: 8,
      critChance: 0.03,
      critMultiplier: 1.5,
      physicalResistance: 0.02,
      fireResistance: 0.05,
    }),
    xpReward: 28,
    contactDamageMin: 5,
    contactDamageMax: 9,
    attackRange: 210,
    attackCooldownMs: 1800,
  },
  bruiser: {
    id: "bruiser",
    name: "Grave Bruiser",
    archetype: "bruiser",
    color: 0x4f8e77,
    radius: 22,
    baseStats: createStatBlock({
      maxHealth: 92,
      healthRegen: 0.2,
      maxEnergy: 0,
      energyRegen: 0,
      armor: 10,
      moveSpeed: 62,
      attackSpeed: 0.7,
      physicalDamageMin: 10,
      physicalDamageMax: 14,
      fireDamageMin: 0,
      fireDamageMax: 0,
      critChance: 0.02,
      critMultiplier: 1.5,
      physicalResistance: 0.07,
      fireResistance: 0.03,
    }),
    xpReward: 38,
    contactDamageMin: 12,
    contactDamageMax: 16,
    attackRange: 44,
    attackCooldownMs: 2200,
  },
  warden: {
    id: "warden",
    name: "Warden Alchemist",
    archetype: "boss",
    color: 0xd8a64f,
    radius: 28,
    baseStats: createStatBlock({
      maxHealth: 340,
      healthRegen: 0.35,
      maxEnergy: 0,
      energyRegen: 0,
      armor: 18,
      moveSpeed: 76,
      attackSpeed: 1,
      physicalDamageMin: 12,
      physicalDamageMax: 18,
      fireDamageMin: 8,
      fireDamageMax: 12,
      critChance: 0.04,
      critMultiplier: 1.65,
      physicalResistance: 0.1,
      fireResistance: 0.12,
    }),
    xpReward: 160,
    contactDamageMin: 14,
    contactDamageMax: 20,
    attackRange: 240,
    attackCooldownMs: 1600,
  },
};
