import type { ItemDefinition } from "../gameplay/types";

export const itemDefinitions: ItemDefinition[] = [
  {
    id: "rusted-rifle",
    name: "Rusted Rifle",
    slot: "weapon",
    rarity: "common",
    baseStats: { physicalDamageMin: 6, physicalDamageMax: 10, attackSpeed: 0.1 },
    affixCapacity: 2,
    requiredLevel: 1,
  },
  {
    id: "brigand-jacket",
    name: "Brigand Jacket",
    slot: "chest",
    rarity: "common",
    baseStats: { armor: 12, maxHealth: 18 },
    affixCapacity: 2,
    requiredLevel: 1,
  },
  {
    id: "charred-band",
    name: "Charred Band",
    slot: "ring",
    rarity: "common",
    baseStats: { fireDamageMin: 1, fireDamageMax: 2, maxEnergy: 10 },
    affixCapacity: 2,
    requiredLevel: 1,
  },
  {
    id: "watchman-carbine",
    name: "Watchman Carbine",
    slot: "weapon",
    rarity: "magic",
    baseStats: { physicalDamageMin: 10, physicalDamageMax: 14, critChance: 0.05 },
    affixCapacity: 2,
    requiredLevel: 2,
  },
  {
    id: "wardens-coat",
    name: "Warden's Coat",
    slot: "chest",
    rarity: "magic",
    baseStats: { armor: 18, maxHealth: 26, fireResistance: 0.05 },
    affixCapacity: 2,
    requiredLevel: 2,
  },
  {
    id: "pyre-loop",
    name: "Pyre Loop",
    slot: "ring",
    rarity: "magic",
    baseStats: { maxEnergy: 14, fireDamageMin: 3, fireDamageMax: 5 },
    affixCapacity: 2,
    requiredLevel: 2,
  },
  {
    id: "militia-repeater",
    name: "Militia Repeater",
    slot: "weapon",
    rarity: "magic",
    baseStats: { physicalDamageMin: 8, physicalDamageMax: 12, attackSpeed: 0.15 },
    affixCapacity: 2,
    requiredLevel: 2,
  },
  {
    id: "blighted-musket",
    name: "Blighted Musket",
    slot: "weapon",
    rarity: "rare",
    baseStats: { physicalDamageMin: 14, physicalDamageMax: 20, poisonResistance: 0.06, critChance: 0.04 },
    affixCapacity: 2,
    requiredLevel: 3,
  },
  {
    id: "hollow-guardian-plate",
    name: "Hollow Guardian Plate",
    slot: "chest",
    rarity: "rare",
    baseStats: { armor: 26, maxHealth: 40, poisonResistance: 0.08, fireResistance: 0.04 },
    affixCapacity: 2,
    requiredLevel: 3,
  },
  {
    id: "frostfire-signet",
    name: "Frostfire Signet",
    slot: "ring",
    rarity: "rare",
    baseStats: { fireDamageMin: 4, fireDamageMax: 7, maxEnergy: 18, critChance: 0.06 },
    affixCapacity: 2,
    requiredLevel: 3,
  },
];
