import type { ZoneDefinition } from "../gameplay/types";

export const zoneDefinitions: Record<string, ZoneDefinition> = {
  crossroads: {
    id: "crossroads",
    name: "Ruined Crossroads",
    width: 1800,
    height: 1200,
    playerSpawn: { x: 240, y: 680 },
    encounters: [
      {
        id: "crossroads-west-pack",
        zoneId: "crossroads",
        spawns: [
          { enemyId: "scavenger", x: 430, y: 560 },
          { enemyId: "scavenger", x: 490, y: 620 },
          { enemyId: "cultist", x: 560, y: 560 },
        ],
      },
      {
        id: "crossroads-center-pack",
        zoneId: "crossroads",
        chest: true,
        spawns: [
          { enemyId: "bruiser", x: 860, y: 440 },
          { enemyId: "cultist", x: 930, y: 390 },
          { enemyId: "scavenger", x: 980, y: 500 },
        ],
      },
      {
        id: "crossroads-east-pack",
        zoneId: "crossroads",
        spawns: [
          { enemyId: "bruiser", x: 1290, y: 720 },
          { enemyId: "cultist", x: 1380, y: 660 },
          { enemyId: "cultist", x: 1450, y: 780 },
        ],
      },
    ],
    transitions: [
      {
        toZoneId: "arena",
        x: 1640,
        y: 470,
        width: 120,
        height: 240,
        targetX: 180,
        targetY: 520,
        label: "To Warden Arena",
      },
      {
        toZoneId: "hollow",
        x: 700,
        y: 1060,
        width: 240,
        height: 100,
        targetX: 200,
        targetY: 180,
        label: "To Blighted Hollow",
      },
      {
        toZoneId: "ashveil",
        x: 1640,
        y: 100,
        width: 120,
        height: 200,
        targetX: 120,
        targetY: 600,
        label: "To Ashveil Descent",
      },
      {
        toZoneId: "town",
        x: 0,
        y: 700,
        width: 64,
        height: 200,
        targetX: 680,
        targetY: 300,
        label: "To Thornhaven",
      },
    ],
  },
  arena: {
    id: "arena",
    name: "Warden Arena",
    width: 1200,
    height: 960,
    playerSpawn: { x: 180, y: 520 },
    encounters: [
      {
        id: "warden-boss",
        zoneId: "arena",
        spawns: [{ enemyId: "warden", x: 820, y: 500 }],
      },
    ],
    transitions: [
      {
        toZoneId: "crossroads",
        x: 0,
        y: 400,
        width: 64,
        height: 240,
        targetX: 1520,
        targetY: 590,
        label: "Back to Crossroads",
      },
    ],
  },
  hollow: {
    id: "hollow",
    name: "Blighted Hollow",
    width: 1600,
    height: 1400,
    playerSpawn: { x: 200, y: 180 },
    encounters: [
      {
        id: "hollow-stalker-pack",
        zoneId: "hollow",
        spawns: [
          { enemyId: "plagueStalker", x: 480, y: 420 },
          { enemyId: "plagueStalker", x: 560, y: 500 },
          { enemyId: "plagueStalker", x: 520, y: 340 },
        ],
      },
      {
        id: "hollow-mixed-pack",
        zoneId: "hollow",
        spawns: [
          { enemyId: "frostWraith", x: 900, y: 680 },
          { enemyId: "frostWraith", x: 1020, y: 740 },
          { enemyId: "plagueStalker", x: 960, y: 600 },
        ],
      },
      {
        id: "hollow-elite-pack",
        zoneId: "hollow",
        chest: true,
        spawns: [
          { enemyId: "bruiser", x: 1180, y: 1050 },
          { enemyId: "cultist", x: 1280, y: 980 },
          { enemyId: "frostWraith", x: 1340, y: 1100 },
          { enemyId: "plagueStalker", x: 1120, y: 1120 },
        ],
      },
    ],
    transitions: [
      {
        toZoneId: "crossroads",
        x: 80,
        y: 0,
        width: 240,
        height: 64,
        targetX: 820,
        targetY: 980,
        label: "Back to Crossroads",
      },
    ],
  },
  ashveil: {
    id: "ashveil",
    name: "Ashveil Descent",
    width: 1600,
    height: 1200,
    playerSpawn: { x: 120, y: 600 },
    encounters: [
      {
        id: "ashveil-entrance-pack",
        zoneId: "ashveil",
        spawns: [
          { enemyId: "scavenger",    x: 320, y: 500 },
          { enemyId: "scavenger",    x: 380, y: 560 },
          { enemyId: "cultist",      x: 450, y: 520 },
          { enemyId: "cultist",      x: 480, y: 600, elite: "armored" },
        ],
      },
      {
        id: "ashveil-mid-pack",
        zoneId: "ashveil",
        chest: true,
        chestX: 850,
        chestY: 600,
        spawns: [
          { enemyId: "bruiser",       x: 780, y: 450 },
          { enemyId: "bruiser",       x: 860, y: 520 },
          { enemyId: "plagueStalker", x: 820, y: 600, elite: "frenzied" },
        ],
      },
      {
        id: "ashveil-deep-pack",
        zoneId: "ashveil",
        spawns: [
          { enemyId: "bruiser",   x: 1200, y: 400, elite: "volatile" },
          { enemyId: "cultist",   x: 1280, y: 480 },
          { enemyId: "cultist",   x: 1340, y: 560 },
          { enemyId: "scavenger", x: 1150, y: 520 },
        ],
      },
    ],
    transitions: [
      {
        toZoneId: "crossroads",
        x: 0,
        y: 400,
        width: 64,
        height: 240,
        targetX: 1520,
        targetY: 590,
        label: "Back to Crossroads",
      },
      {
        toZoneId: "deepmire",
        x: 1536,
        y: 400,
        width: 64,
        height: 240,
        targetX: 120,
        targetY: 600,
        label: "To Deepmire Caverns",
      },
    ],
  },
  deepmire: {
    id: "deepmire",
    name: "Deepmire Caverns",
    width: 1800,
    height: 1400,
    playerSpawn: { x: 120, y: 600 },
    encounters: [
      {
        id: "deepmire-stalker-pack",
        zoneId: "deepmire",
        chest: true,
        chestX: 500,
        chestY: 400,
        spawns: [
          { enemyId: "plagueStalker", x: 300, y: 280 },
          { enemyId: "plagueStalker", x: 380, y: 350 },
          { enemyId: "plagueStalker", x: 440, y: 260 },
          { enemyId: "plagueStalker", x: 350, y: 420, elite: "empowered" },
        ],
      },
      {
        id: "deepmire-wraith-pack",
        zoneId: "deepmire",
        spawns: [
          { enemyId: "frostWraith", x: 860,  y: 660 },
          { enemyId: "frostWraith", x: 940,  y: 720 },
          { enemyId: "frostWraith", x: 900,  y: 760, elite: "armored" },
          { enemyId: "bruiser",     x: 1000, y: 680 },
        ],
      },
      {
        id: "deepmire-boss-pack",
        zoneId: "deepmire",
        chest: true,
        chestX: 1350,
        chestY: 1050,
        spawns: [
          { enemyId: "bruiser",       x: 1350, y: 980,  elite: "regenerating" },
          { enemyId: "plagueStalker", x: 1280, y: 1060 },
          { enemyId: "plagueStalker", x: 1420, y: 1040 },
          { enemyId: "cultist",       x: 1480, y: 980,  elite: "frenzied" },
        ],
      },
    ],
    transitions: [
      {
        toZoneId: "ashveil",
        x: 0,
        y: 500,
        width: 64,
        height: 240,
        targetX: 1480,
        targetY: 600,
        label: "Back to Ashveil",
      },
    ],
  },
  town: {
    id: "town",
    name: "Thornhaven",
    width: 800,
    height: 600,
    playerSpawn: { x: 120, y: 300 },
    encounters: [],
    transitions: [
      {
        toZoneId: "crossroads",
        x: 0,
        y: 200,
        width: 64,
        height: 200,
        targetX: 120,
        targetY: 760,
        label: "Back to Crossroads",
      },
    ],
  },
};
